# Generated by Django 3.0.8 on 2020-12-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201215_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_delivery_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_name',
        ),
    ]
