# Generated by Django 3.0.8 on 2020-12-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201219_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=10, null=True),
        ),
    ]
