# Generated by Django 3.0.8 on 2020-12-24 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
